// This file is auto-generated by @hey-api/openapi-ts

import { type Options, appControllerGetHello, getWalletCredentials, addWalletCredential, deleteWalletCredential, getWalletCredentialById } from '../sdk.gen';
import { queryOptions, infiniteQueryOptions, type InfiniteData, type DefaultError, type UseMutationOptions } from '@tanstack/react-query';
import type { AppControllerGetHelloData, GetWalletCredentialsData, GetWalletCredentialsResponse, AddWalletCredentialData, AddWalletCredentialResponse, DeleteWalletCredentialData, GetWalletCredentialByIdData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await appControllerGetHello({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: appControllerGetHelloQueryKey(options)
    });
};

export const getWalletCredentialsQueryKey = (options?: Options<GetWalletCredentialsData>) => createQueryKey('getWalletCredentials', options);

export const getWalletCredentialsOptions = (options?: Options<GetWalletCredentialsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWalletCredentials({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWalletCredentialsQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = queryKey[0];
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getWalletCredentialsInfiniteQueryKey = (options?: Options<GetWalletCredentialsData>): QueryKey<Options<GetWalletCredentialsData>> => createQueryKey('getWalletCredentials', options, true);

export const getWalletCredentialsInfiniteOptions = (options?: Options<GetWalletCredentialsData>) => {
    return infiniteQueryOptions<GetWalletCredentialsResponse, DefaultError, InfiniteData<GetWalletCredentialsResponse>, QueryKey<Options<GetWalletCredentialsData>>, number | Pick<QueryKey<Options<GetWalletCredentialsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetWalletCredentialsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getWalletCredentials({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWalletCredentialsInfiniteQueryKey(options)
    });
};

export const addWalletCredentialQueryKey = (options: Options<AddWalletCredentialData>) => createQueryKey('addWalletCredential', options);

export const addWalletCredentialOptions = (options: Options<AddWalletCredentialData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addWalletCredential({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addWalletCredentialQueryKey(options)
    });
};

export const addWalletCredentialMutation = (options?: Partial<Options<AddWalletCredentialData>>) => {
    const mutationOptions: UseMutationOptions<AddWalletCredentialResponse, DefaultError, Options<AddWalletCredentialData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addWalletCredential({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteWalletCredentialMutation = (options?: Partial<Options<DeleteWalletCredentialData>>) => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteWalletCredentialData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteWalletCredential({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWalletCredentialByIdQueryKey = (options: Options<GetWalletCredentialByIdData>) => createQueryKey('getWalletCredentialById', options);

export const getWalletCredentialByIdOptions = (options: Options<GetWalletCredentialByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWalletCredentialById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWalletCredentialByIdQueryKey(options)
    });
};