// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { AppControllerGetHelloData, GetWalletCredentialsData, GetWalletCredentialsResponse, AddWalletCredentialData, AddWalletCredentialResponse, DeleteWalletCredentialData, GetWalletCredentialByIdData, GetWalletCredentialByIdResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Get paginated wallet credentials
 */
export const getWalletCredentials = <ThrowOnError extends boolean = false>(options?: Options<GetWalletCredentialsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetWalletCredentialsResponse, unknown, ThrowOnError>({
        url: '/wallet/credentials',
        ...options
    });
};

/**
 * Create a new wallet credential
 */
export const addWalletCredential = <ThrowOnError extends boolean = false>(options: Options<AddWalletCredentialData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddWalletCredentialResponse, unknown, ThrowOnError>({
        url: '/wallet/credentials',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a wallet credential
 */
export const deleteWalletCredential = <ThrowOnError extends boolean = false>(options: Options<DeleteWalletCredentialData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        url: '/wallet/credentials/{id}',
        ...options
    });
};

/**
 * Get a wallet credential by ID
 */
export const getWalletCredentialById = <ThrowOnError extends boolean = false>(options: Options<GetWalletCredentialByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetWalletCredentialByIdResponse, unknown, ThrowOnError>({
        url: '/wallet/credentials/{id}',
        ...options
    });
};