// This file is auto-generated by @hey-api/openapi-ts

export type WalletCredential = {
    /**
     * The ID of the wallet credential
     */
    id: string;
    /**
     * The name of the wallet credential
     */
    name: string;
    /**
     * The context of the wallet credential
     */
    context: Array<string>;
    /**
     * The issuance date of the wallet credential
     */
    issuanceDate: string;
    /**
     * The expiration date of the wallet credential
     */
    expirationDate: string;
    /**
     * The raw data of the wallet credential
     */
    raw: {
        [key: string]: unknown;
    };
};

export type Pagination = {
    /**
     * The total number of items
     */
    total: number;
    /**
     * The current page number
     */
    page: number;
    /**
     * The number of items per page
     */
    limit: number;
    /**
     * The total number of pages
     */
    pages: number;
};

export type PaginatedWalletCredentialsResponse = {
    /**
     * The wallet credentials
     */
    credentials: Array<WalletCredential>;
    /**
     * The pagination information
     */
    pagination: Pagination;
};

export type CreateWalletCredential = {
    /**
     * The name of the wallet credential
     */
    name: string;
    /**
     * The context of the wallet credential
     */
    context: Array<string>;
    /**
     * The issuance date of the wallet credential
     */
    issuanceDate: string;
    /**
     * The expiration date of the wallet credential
     */
    expirationDate: string;
    /**
     * The raw data of the wallet credential
     */
    raw: {
        [key: string]: unknown;
    };
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type GetWalletCredentialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/wallet/credentials';
};

export type GetWalletCredentialsResponses = {
    /**
     * Returns paginated credentials
     */
    200: PaginatedWalletCredentialsResponse;
};

export type GetWalletCredentialsResponse = GetWalletCredentialsResponses[keyof GetWalletCredentialsResponses];

export type CreateWalletCredentialData = {
    body: CreateWalletCredential;
    path?: never;
    query?: never;
    url: '/wallet/credentials';
};

export type CreateWalletCredentialErrors = {
    /**
     * Bad request - invalid credential data
     */
    400: unknown;
};

export type CreateWalletCredentialResponses = {
    /**
     * Credential created successfully
     */
    201: WalletCredential;
};

export type CreateWalletCredentialResponse = CreateWalletCredentialResponses[keyof CreateWalletCredentialResponses];

export type DeleteWalletCredentialData = {
    body?: never;
    path: {
        /**
         * Credential ID
         */
        id: string;
    };
    query?: never;
    url: '/wallet/credentials/{id}';
};

export type DeleteWalletCredentialErrors = {
    /**
     * Credential not found
     */
    404: unknown;
};

export type DeleteWalletCredentialResponses = {
    /**
     * Credential deleted successfully
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};